# general settings
name: train_ModMBFormer_Sim_DSF_ImageNet_DF2K
model_type: HATModel
scale: 8
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: DSF_DF2K_Dataset
    dataroot_gt: datasets/DF2K_HR
    io_backend:
      type: disk

    patch_size: 48
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 20
    prefetch_mode: ~

  val_1:
    name: Set5x4
    type: DSF_val_Dataset
    dataroot_gt: datasets/benchmark/Set5/HR
    dataroot_lq: datasets/benchmark/Set5/LR_bicubic/X4
    io_backend:
      type: disk

  val_2:
    name: Set5x8
    type: DSF_val_downsample_Dataset
    dataroot_gt: datasets/benchmark/Set5/HR
    # dataroot_lq: ./datasets/Set14/LRbicx2
    io_backend:
      type: disk

  # val_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/urban100/GTmod2
  #   dataroot_lq: ./datasets/urban100/LRbicx2
  #   io_backend:
  #     type: disk


# network structures
network_g:
  type: EQSR
  upscale: 3
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [5, 5, 5, 5, 5, 5]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ./experiments/train_ModMBFormer_Sim_DSF_ImageNet_from_scratch/models/net_g_latest.pth
  param_key_g: 'params_ema'
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 225000, 240000]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 3
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 3
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
